export const FRAME_RATE = 30;
export const INTRO_DURATION_S = 6;
export const OUTRO_DURATION_S = 21;
export const CREDITS_START_S = 285;  // 4:45，固定絕對時間點（會疊在 Outro 尾段上）
export const CREDITS_DURATION_S = 9; // 285~294s，縮短後省下的時間讓給 Finale
export const FINALE_START_S = CREDITS_START_S + CREDITS_DURATION_S; // 294s，Credits 結束後緊接
export const FINALE_DURATION_S = 26; // 294~320s，即 4:54~5:20，全體Q版大頭貼跑馬燈彩蛋（總長仍鎖 320s）
export const AVATAR_COUNT = 580;     // 對應 data/face-selection.json 的 keepFiles 數量
export const SECTION_TITLE_DURATION_S = 3.5;
export const LYRIC_DURATION_S = 3;
export const DEFAULT_PHOTO_DURATION_S = 3;
export const HIGH_IMPORTANCE_PHOTO_DURATION_S = 3;
export const MONTAGE_PHOTO_DURATION_S = 1.5;
